document.body.innerHTML = "";
document.write('<!DOCTYPE html>');
document.write('<html>');
document.write('<head>');
document.write('  <title>Basic Snake HTML Game</title>');
document.write('  <meta charset="UTF-8">');
document.write('  <style>');
document.write('  html, body {');
document.write('    height: 100%;');
document.write('    margin: 0;');
document.write('  }');
document.write('');
document.write('  body {');
document.write('    background: black;');
document.write('    display: flex;');
document.write('    align-items: center;');
document.write('    justify-content: center;');
document.write('  }');
document.write('  canvas {');
document.write('    border: 1px solid white;');
document.write('  }');
document.write('  </style>');
document.write('</head>');
document.write('<body>');
document.write('<canvas width="400" height="400" id="game"></canvas>');
document.write('<script>');
document.write('var canvas = document.getElementById(\'game\');');
document.write('var context = canvas.getContext(\'2d\');');
document.write('');
document.write('// the canvas width & height, snake x & y, and the apple x & y, all need to be a multiples of the grid size in order for collision detection to work');
document.write('// (e.g. 16 * 25 = 400)');
document.write('var grid = 16;');
document.write('var count = 0;');
document.write('');
document.write('var snake = {');
document.write('  x: 160,');
document.write('  y: 160,');
document.write('');
document.write('  // snake velocity. moves one grid length every frame in either the x or y direction');
document.write('  dx: grid,');
document.write('  dy: 0,');
document.write('');
document.write('  // keep track of all grids the snake body occupies');
document.write('  cells: [],');
document.write('');
document.write('  // length of the snake. grows when eating an apple');
document.write('  maxCells: 4');
document.write('};');
document.write('var apple = {');
document.write('  x: 320,');
document.write('  y: 320');
document.write('};');
document.write('');
document.write('// get random whole numbers in a specific range');
document.write('// @see https://stackoverflow.com/a/1527820/2124254');
document.write('function getRandomInt(min, max) {');
document.write('  return Math.floor(Math.random() * (max - min)) + min;');
document.write('}');
document.write('');
document.write('// game loop');
document.write('function loop() {');
document.write('  requestAnimationFrame(loop);');
document.write('');
document.write('  // slow game loop to 15 fps instead of 60 (60/15 = 4)');
document.write('  if (++count < 4) {');
document.write('    return;');
document.write('  }');
document.write('');
document.write('  count = 0;');
document.write('  context.clearRect(0,0,canvas.width,canvas.height);');
document.write('');
document.write('  // move snake by it\'s velocity');
document.write('  snake.x += snake.dx;');
document.write('  snake.y += snake.dy;');
document.write('');
document.write('  // wrap snake position horizontally on edge of screen');
document.write('  if (snake.x < 0) {');
document.write('    snake.x = canvas.width - grid;');
document.write('  }');
document.write('  else if (snake.x >= canvas.width) {');
document.write('    snake.x = 0;');
document.write('  }');
document.write('');
document.write('  // wrap snake position vertically on edge of screen');
document.write('  if (snake.y < 0) {');
document.write('    snake.y = canvas.height - grid;');
document.write('  }');
document.write('  else if (snake.y >= canvas.height) {');
document.write('    snake.y = 0;');
document.write('  }');
document.write('');
document.write('  // keep track of where snake has been. front of the array is always the head');
document.write('  snake.cells.unshift({x: snake.x, y: snake.y});');
document.write('');
document.write('  // remove cells as we move away from them');
document.write('  if (snake.cells.length > snake.maxCells) {');
document.write('    snake.cells.pop();');
document.write('  }');
document.write('');
document.write('  // draw apple');
document.write('  context.fillStyle = \'red\';');
document.write('  context.fillRect(apple.x, apple.y, grid-1, grid-1);');
document.write('');
document.write('  // draw snake one cell at a time');
document.write('  context.fillStyle = \'green\';');
document.write('  snake.cells.forEach(function(cell, index) {');
document.write('');
document.write('    // drawing 1 px smaller than the grid creates a grid effect in the snake body so you can see how long it is');
document.write('    context.fillRect(cell.x, cell.y, grid-1, grid-1);');
document.write('');
document.write('    // snake ate apple');
document.write('    if (cell.x === apple.x && cell.y === apple.y) {');
document.write('      snake.maxCells++;');
document.write('');
document.write('      // canvas is 400x400 which is 25x25 grids');
document.write('      apple.x = getRandomInt(0, 25) * grid;');
document.write('      apple.y = getRandomInt(0, 25) * grid;');
document.write('    }');
document.write('');
document.write('    // check collision with all cells after this one (modified bubble sort)');
document.write('    for (var i = index + 1; i < snake.cells.length; i++) {');
document.write('');
document.write('      // snake occupies same space as a body part. reset game');
document.write('      if (cell.x === snake.cells[i].x && cell.y === snake.cells[i].y) {');
document.write('        snake.x = 160;');
document.write('        snake.y = 160;');
document.write('        snake.cells = [];');
document.write('        snake.maxCells = 4;');
document.write('        snake.dx = grid;');
document.write('        snake.dy = 0;');
document.write('');
document.write('        apple.x = getRandomInt(0, 25) * grid;');
document.write('        apple.y = getRandomInt(0, 25) * grid;');
document.write('      }');
document.write('    }');
document.write('  });');
document.write('}');
document.write('');
document.write('// listen to keyboard events to move the snake');
document.write('document.addEventListener(\'keydown\', function(e) {');
document.write('  // prevent snake from backtracking on itself by checking that it\'s');
document.write('  // not already moving on the same axis (pressing left while moving');
document.write('  // left won\'t do anything, and pressing right while moving left');
document.write('  // shouldn\'t let you collide with your own body)');
document.write('');
document.write('  // left arrow key');
document.write('  if (e.which === 37 && snake.dx === 0) {');
document.write('    snake.dx = -grid;');
document.write('    snake.dy = 0;');
document.write('  }');
document.write('  // up arrow key');
document.write('  else if (e.which === 38 && snake.dy === 0) {');
document.write('    snake.dy = -grid;');
document.write('    snake.dx = 0;');
document.write('  }');
document.write('  // right arrow key');
document.write('  else if (e.which === 39 && snake.dx === 0) {');
document.write('    snake.dx = grid;');
document.write('    snake.dy = 0;');
document.write('  }');
document.write('  // down arrow key');
document.write('  else if (e.which === 40 && snake.dy === 0) {');
document.write('    snake.dy = grid;');
document.write('    snake.dx = 0;');
document.write('  }');
document.write('});');
document.write('');
document.write('// start the game');
document.write('requestAnimationFrame(loop);');
document.write('</script>');
document.write('</body>');
document.write('</html>');
